# Generated by Django 4.2.7 on 2023-12-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedvalue',
            name='interval',
            field=models.IntegerField(default=0),
        ),
    ]
